# Generated by Django 5.2 on 2025-07-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idoma_app', '0002_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='donor_name',
        ),
        migrations.AddField(
            model_name='donations',
            name='reference',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donations',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donations',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
