# Generated by Django 5.2 on 2025-07-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idoma_app', '0003_remove_donations_donor_name_donations_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
