# Generated by Django 5.2 on 2025-07-19 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idoma_app', '0004_donations_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='donation_date',
        ),
        migrations.AddField(
            model_name='donations',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='donations',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donations',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
