# Generated by Django 5.2 on 2025-07-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idoma_app', '0005_remove_donations_donation_date_donations_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donations',
        ),
    ]
