# Generated by Django 5.2 on 2025-07-23 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idoma_app', '0008_member_partnership_volunteer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Events',
        ),
    ]
