# Generated by Django 5.2 on 2025-07-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idoma_app', '0011_forumtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
